name: Example GitHub Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 22ds3000188@ds.study.iitm.ac.in
        run: echo "Hello, world!"
